export const LIST_RAMDOMIZED = 'LIST_RAMDOMIZED';
export const LIST_SORTED = 'LIST_SORTED';

export const PROCESS_START = 'PROCESS_START';
export const PROCESS_END = 'PROCESS_END';

export const UPDATE_SECTION = 'UPDATE_SECTION';
export const UPDATE_LENGTH = 'UPDATE_LENGTH';
export const UPDATE_SPEED = 'UPDATE_SPEED';

export const UPDATE_LIST = 'UPDATE_LIST';
export const UPDATE_COMPARING_NODE = 'UPDATE_COMPARING_NODE';
export const UPDATE_COMPARING_LIST = 'UPDATE_COMPARING_LIST';